# Azure pipeline for eNPL

# Only build the master branch, tags, and PRs (on by default) to avoid building random
# branches in the repository until a PR is opened.
trigger:
  branches:
    include:
    - master
    - refs/tags/*

jobs:


# Linux
########################################################################################
- job:
  displayName: 'Linux'

  pool:
    vmImage: 'ubuntu-16.04'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
      architecture: 'x64'

  - script: |
      python -m pip install --upgrade pip setuptools wheel django
      pip install -r requirements-dev.txt
      pip install .
    displayName: 'Install prerequisites and library'

  - script: |
      python setup.py test
    condition: succeededOrFailed()
    displayName: 'Run tests'


# Windows
########################################################################################
- job:
  displayName: 'Windows'

  pool:
    vmImage: 'vs2017-win2016'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
      architecture: 'x64'

  - script: |
      python -m pip install --upgrade pip setuptools wheel django
      pip install -r requirements-dev.txt
      pip install .
    displayName: 'Install prerequisites and library'
  - script: |
      python setup.py test
    condition: succeededOrFailed()
    displayName: 'Run tests'


# Mac
########################################################################################
- job:
  displayName: 'Mac'

  pool:
    vmImage: 'macOS-10.14'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
      architecture: 'x64'

  - script: |
      python -m pip install --upgrade pip setuptools wheel django
      pip install -r requirements-dev.txt
      pip install .
    displayName: 'Install prerequisites and library'
  - script: |
      python setup.py test
    condition: succeededOrFailed()
    displayName: 'Run tests'