name: enlp
channels:
  - defaults
dependencies:
  - python>=3.5
  - numpy
  - matplotlib
  - pandas
  - pytest
  - pytest-cov
  - nltk
  - spacy
  - Sphinx
  - numpydoc
  - scikit-learn
  - gensim
  - pip:
      - https://github.com/ohenrik/nb_dep_ud_sm/raw/master/nb_dep_ud_sm-0.0.1/dist/nb_dep_ud_sm-0.0.1.tar.gz
      - https://github.com/explosion/spacy-models/releases/download/en_core_web_md-2.0.0/en_core_web_md-2.0.0.tar.gz
      - pytest-runner
      - setuptools_scm
      - sphinx-rtd-theme
      - sphinx-gallery
      - nbsphinx
      - image
      - wordcloud
      - rake-nltk